name=input("Please provide your Name: ")
age=int(input("Please provide your Age: "))
profession=input("Please Enter your Profession: ")
place=input("Please Enter where you are from: ")
print(f"Hello {name}. You are {age} years old.")
print(f"Your profession is {profession}")
print(f"You are from {place}")
print("Thankyou very much")
print("----------------******************------------------")
print("malli kaluddam")
print("inka selavu")